### ISSUE TITLE
[Docs] add depedency testImplementation block for build.gradle.kts

### ISSUE THREAD

**Issue by heli-os** [specmock/specmock#6]
## Motivation
- Can also build gradle with build.gradle.kts
- and [Kotlin DSL is now the Default for New Gradle Builds]( https://blog.jetbrains.com/kotlin/2023/04/kotlin-dsl-is-the-default-for-new-gradle-builds/)

**Comment by geminiKim** [comment]
Wow, the default is now Kotlin DSL, I guess we'll have to migrate at the appropriate time. 👍
